/* ---------------------------------------------------------------------
 *
 *  -- AOCL ScaLAPACK Wrappers --
 *     Copyright (c) 2025 Advanced Micro Devices, Inc.  All rights reserved.
 *
 *  ---------------------------------------------------------------------
 */

/* Auto-generated: DO NOT EDIT MANUALLY
 * Generated by SCRIPTS/generate_mangling_header.py
 */
#ifndef AOCL_TOOLS_MANGLE_FUNCTION_PROTOTYPES_H
#define AOCL_TOOLS_MANGLE_FUNCTION_PROTOTYPES_H

#ifdef _WIN32
/* On Windows: Fortran symbols built (forced) as lowercase without underscore.
 * F77_<UPPER>  => undecorated
 * mangle_<lower> => trailing underscore form
 */

#define F77_SL_INIT                  sl_init
#define mangle_sl_init               sl_init_

#define F77_SLBOOT                   slboot
#define mangle_slboot                slboot_

#define F77_SLENABLE                 slenable
#define mangle_slenable              slenable_

#define F77_SLDISABLE                sldisable
#define mangle_sldisable             sldisable_

#define F77_SLINQUIRE                slinquire
#define mangle_slinquire             slinquire_

#define F77_SL_COMBINE               slcombine
#define mangle_sl_combine            slcombine_

#define F77_CCDOTC                   ccdotc
#define mangle_ccdotc                ccdotc_

#define F77_CCDOTU                   ccdotu
#define mangle_ccdotu                ccdotu_

#define F77_CHK1MAT                  chk1mat
#define mangle_chk1mat               chk1mat_

#define F77_CLATCPY                  clatcpy
#define mangle_clatcpy               clatcpy_

#define F77_CMATADD                  cmatadd
#define mangle_cmatadd               cmatadd_

#define F77_DDDOT                    dddot
#define mangle_dddot                 dddot_

#define F77_DESC_CONVERT             desc_convert
#define mangle_desc_convert          desc_convert_

#define F77_DESCINIT                 descinit
#define mangle_descinit              descinit_

#define F77_DESCSET                  descset
#define mangle_descset               descset_

#define F77_DLATCPY                  dlatcpy
#define mangle_dlatcpy               dlatcpy_

#define F77_DMATADD                  dmatadd
#define mangle_dmatadd               dmatadd_

#define F77_DSASUM                   dsasum
#define mangle_dsasum                dsasum_

#define F77_DSCASUM                  dscasum
#define mangle_dscasum               dscasum_

#define F77_DSCNRM2                  dscnrm2
#define mangle_dscnrm2               dscnrm2_

#define F77_DSNRM2                   dsnrm2
#define mangle_dsnrm2                dsnrm2_

#define F77_ICEIL                    iceil
#define mangle_iceil                 iceil_

#define F77_ILACPY                   ilacpy
#define mangle_ilacpy                ilacpy_

#define F77_ILCM                     ilcm
#define mangle_ilcm                  ilcm_

#define F77_INDXG2L                  indxg2l
#define mangle_indxg2l               indxg2l_

#define F77_INDXG2P                  indxg2p
#define mangle_indxg2p               indxg2p_

#define F77_INDXL2G                  indxl2g
#define mangle_indxl2g               indxl2g_

#define F77_INFOG1L                  infog1l
#define mangle_infog1l               infog1l_

#define F77_INFOG2L                  infog2l
#define mangle_infog2l               infog2l_

#define F77_NPREROC                  npreroc
#define mangle_npreroc               npreroc_

#define F77_NUMROC                   numroc
#define mangle_numroc                numroc_

#define F77_PCCHEKPAD                pcchekpad
#define mangle_pcchekpad             pcchekpad_

#define F77_PCHK1MAT                  pchk1mat
#define mangle_pchk1mat               pchk1mat_

#define F77_PCCOL2ROW                pccol2row
#define mangle_pccol2row             pccol2row_

#define F77_PCELGET                  pcelget
#define mangle_pcelget               pcelget_

#define F77_PCELSET                  pcelset
#define mangle_pcelset               pcelset_

#define F77_PCELSET2                 pcelset2
#define mangle_pcelset2              pcelset2_

#define F77_PCFILLPAD                pcfillpad
#define mangle_pcfillpad             pcfillpad_

#define F77_PCHKXMAT                 pchkxmat
#define mangle_pchkxmat              pchkxmat_

#define F77_PCLAPRNT                 pclaprnt
#define mangle_pclaprnt              pclaprnt_

#define F77_PCLAREAD                 pclaread
#define mangle_pclaread              pclaread_

#define F77_PCLAWRITE                pclawrite
#define mangle_pclawrite             pclawrite_

#define F77_PCMATADD                 pcmatadd
#define mangle_pcmatadd              pcmatadd_

#define F77_PCROW2COL                pcrow2col
#define mangle_pcrow2col             pcrow2col_

#define F77_PCTREECOMB               pctreecomb
#define mangle_pctreecomb            pctreecomb_

#define F77_PDCHEKPAD                pdchekpad
#define mangle_pdchekpad             pdchekpad_

#define F77_PDCOL2ROW                pdcol2row
#define mangle_pdcol2row             pdcol2row_

#define F77_PDELGET                  pdelget
#define mangle_pdelget               pdelget_

#define F77_PDELSET                  pdelset
#define mangle_pdelset               pdelset_

#define F77_PDELSET2                 pdelset2
#define mangle_pdelset2              pdelset2_

#define F77_PDFILLPAD                pdfillpad
#define mangle_pdfillpad             pdfillpad_

#define F77_PDLAPRNT                 pdlaprnt
#define mangle_pdlaprnt              pdlaprnt_

#define F77_PDLAREAD                 pdlaread
#define mangle_pdlaread              pdlaread_

#define F77_PDLAWRITE                pdlawrite
#define mangle_pdlawrite             pdlawrite_

#define F77_PDMATADD                 pdmatadd
#define mangle_pdmatadd              pdmatadd_

#define F77_PDROW2COL                pdrow2col
#define mangle_pdrow2col             pdrow2col_

#define F77_PDTREECOMB               pdtreecomb
#define mangle_pdtreecomb            pdtreecomb_

#define F77_PICHEKPAD                pichekpad
#define mangle_pichekpad             pichekpad_

#define F77_PICOL2ROW                picol2row
#define mangle_picol2row             picol2row_

#define F77_PIELGET                  pielget
#define mangle_pielget               pielget_

#define F77_PIELSET                  pielset
#define mangle_pielset               pielset_

#define F77_PIELSET2                 pielset2
#define mangle_pielset2              pielset2_

#define F77_PIFILLPAD                pifillpad
#define mangle_pifillpad             pifillpad_

#define F77_PILAPRNT                 pilaprnt
#define mangle_pilaprnt              pilaprnt_

#define F77_PIROW2COL                pirow2col
#define mangle_pirow2col             pirow2col_

#define F77_PITREECOMB               pitreecomb
#define mangle_pitreecomb            pitreecomb_

#define F77_PSCHEKPAD                pschekpad
#define mangle_pschekpad             pschekpad_

#define F77_PSCOL2ROW                pscol2row
#define mangle_pscol2row             pscol2row_

#define F77_PSELGET                  pselget
#define mangle_pselget               pselget_

#define F77_PSELSET                  pselset
#define mangle_pselset               pselset_

#define F77_PSELSET2                 pselset2
#define mangle_pselset2              pselset2_

#define F77_PSFILLPAD                psfillpad
#define mangle_psfillpad             psfillpad_

#define F77_PSLAPRNT                 pslaprnt
#define mangle_pslaprnt              pslaprnt_

#define F77_PSLAREAD                 pslaread
#define mangle_pslaread              pslaread_

#define F77_PSLAWRITE                pslawrite
#define mangle_pslawrite             pslawrite_

#define F77_PSMATADD                 psmatadd
#define mangle_psmatadd              psmatadd_

#define F77_PSROW2COL                psrow2col
#define mangle_psrow2col             psrow2col_

#define F77_PSTREECOMB               pstreecomb
#define mangle_pstreecomb            pstreecomb_

#define F77_PZCHEKPAD                pzchekpad
#define mangle_pzchekpad             pzchekpad_

#define F77_PZCOL2ROW                pzcol2row
#define mangle_pzcol2row             pzcol2row_

#define F77_PZELGET                  pzelget
#define mangle_pzelget               pzelget_

#define F77_PZELSET                  pzelset
#define mangle_pzelset               pzelset_

#define F77_PZELSET2                 pzelset2
#define mangle_pzelset2              pzelset2_

#define F77_PZFILLPAD                pzfillpad
#define mangle_pzfillpad             pzfillpad_

#define F77_PZLAPRNT                 pzlaprnt
#define mangle_pzlaprnt              pzlaprnt_

#define F77_PZLAREAD                 pzlaread
#define mangle_pzlaread              pzlaread_

#define F77_PZLAWRITE                pzlawrite
#define mangle_pzlawrite             pzlawrite_

#define F77_PZMATADD                 pzmatadd
#define mangle_pzmatadd              pzmatadd_

#define F77_PZROW2COL                pzrow2col
#define mangle_pzrow2col             pzrow2col_

#define F77_PZTREECOMB               pztreecomb
#define mangle_pztreecomb            pztreecomb_

#define F77_SLATCPY                  slatcpy
#define mangle_slatcpy               slatcpy_

#define F77_SLTIMER                  sltimer
#define mangle_sltimer               sltimer_

#define F77_SMATADD                  smatadd
#define mangle_smatadd               smatadd_

#define F77_SSDOT                    ssdot
#define mangle_ssdot                 ssdot_

#define F77_ZLATCPY                  zlatcpy
#define mangle_zlatcpy               zlatcpy_

#define F77_ZMATADD                  zmatadd
#define mangle_zmatadd               zmatadd_

#define F77_ZZDOTC                   zzdotc
#define mangle_zzdotc                zzdotc_

#define F77_ZZDOTU                   zzdotu
#define mangle_zzdotu                zzdotu_


#else
/* On non-Windows (Linux/Unix): Fortran symbols use lowercase with trailing underscore.
 * F77_<UPPER>  => with underscore
 * mangle_<lower> => undecorated form
 */

#define F77_SL_INIT                  sl_init_
#define mangle_sl_init               sl_init

#define F77_SLBOOT                   slboot_
#define mangle_slboot                slboot

#define F77_SLENABLE                 slenable_
#define mangle_slenable              slenable

#define F77_SLDISABLE                sldisable_
#define mangle_sldisable             sldisable

#define F77_SLINQUIRE                slinquire_
#define mangle_slinquire             slinquire

#define F77_SL_COMBINE               slcombine_
#define mangle_sl_combine            slcombine

#define F77_CCDOTC                   ccdotc_
#define mangle_ccdotc                ccdotc

#define F77_CCDOTU                   ccdotu_
#define mangle_ccdotu                ccdotu

#define F77_CHK1MAT                  chk1mat_
#define mangle_chk1mat               chk1mat

#define F77_CLATCPY                  clatcpy_
#define mangle_clatcpy               clatcpy

#define F77_CMATADD                  cmatadd_
#define mangle_cmatadd               cmatadd

#define F77_DDDOT                    dddot_
#define mangle_dddot                 dddot

#define F77_DESC_CONVERT             desc_convert_
#define mangle_desc_convert          desc_convert

#define F77_DESCINIT                 descinit_
#define mangle_descinit              descinit

#define F77_DESCSET                  descset_
#define mangle_descset               descset

#define F77_DLATCPY                  dlatcpy_
#define mangle_dlatcpy               dlatcpy

#define F77_DMATADD                  dmatadd_
#define mangle_dmatadd               dmatadd

#define F77_DSASUM                   dsasum_
#define mangle_dsasum                dsasum

#define F77_DSCASUM                  dscasum_
#define mangle_dscasum               dscasum

#define F77_DSCNRM2                  dscnrm2_
#define mangle_dscnrm2               dscnrm2

#define F77_DSNRM2                   dsnrm2_
#define mangle_dsnrm2                dsnrm2

#define F77_ICEIL                    iceil_
#define mangle_iceil                 iceil

#define F77_ILACPY                   ilacpy_
#define mangle_ilacpy                ilacpy

#define F77_ILCM                     ilcm_
#define mangle_ilcm                  ilcm

#define F77_INDXG2L                  indxg2l_
#define mangle_indxg2l               indxg2l

#define F77_INDXG2P                  indxg2p_
#define mangle_indxg2p               indxg2p

#define F77_INDXL2G                  indxl2g_
#define mangle_indxl2g               indxl2g

#define F77_INFOG1L                  infog1l_
#define mangle_infog1l               infog1l

#define F77_INFOG2L                  infog2l_
#define mangle_infog2l               infog2l

#define F77_NPREROC                  npreroc_
#define mangle_npreroc               npreroc

#define F77_NUMROC                   numroc_
#define mangle_numroc                numroc

#define F77_PCCHEKPAD                pcchekpad_
#define mangle_pcchekpad             pcchekpad

#define F77_PCHK1MAT                  pchk1mat_
#define mangle_pchk1mat               pchk1mat

#define F77_PCCOL2ROW                pccol2row_
#define mangle_pccol2row             pccol2row

#define F77_PCELGET                  pcelget_
#define mangle_pcelget               pcelget

#define F77_PCELSET                  pcelset_
#define mangle_pcelset               pcelset

#define F77_PCELSET2                 pcelset2_
#define mangle_pcelset2              pcelset2

#define F77_PCFILLPAD                pcfillpad_
#define mangle_pcfillpad             pcfillpad

#define F77_PCHKXMAT                 pchkxmat_
#define mangle_pchkxmat              pchkxmat

#define F77_PCLAPRNT                 pclaprnt_
#define mangle_pclaprnt              pclaprnt

#define F77_PCLAREAD                 pclaread_
#define mangle_pclaread              pclaread

#define F77_PCLAWRITE                pclawrite_
#define mangle_pclawrite             pclawrite

#define F77_PCMATADD                 pcmatadd_
#define mangle_pcmatadd              pcmatadd

#define F77_PCROW2COL                pcrow2col_
#define mangle_pcrow2col             pcrow2col

#define F77_PCTREECOMB               pctreecomb_
#define mangle_pctreecomb            pctreecomb

#define F77_PDCHEKPAD                pdchekpad_
#define mangle_pdchekpad             pdchekpad

#define F77_PDCOL2ROW                pdcol2row_
#define mangle_pdcol2row             pdcol2row

#define F77_PDELGET                  pdelget_
#define mangle_pdelget               pdelget

#define F77_PDELSET                  pdelset_
#define mangle_pdelset               pdelset

#define F77_PDELSET2                 pdelset2_
#define mangle_pdelset2              pdelset2

#define F77_PDFILLPAD                pdfillpad_
#define mangle_pdfillpad             pdfillpad

#define F77_PDLAPRNT                 pdlaprnt_
#define mangle_pdlaprnt              pdlaprnt

#define F77_PDLAREAD                 pdlaread_
#define mangle_pdlaread              pdlaread

#define F77_PDLAWRITE                pdlawrite_
#define mangle_pdlawrite             pdlawrite

#define F77_PDMATADD                 pdmatadd_
#define mangle_pdmatadd              pdmatadd

#define F77_PDROW2COL                pdrow2col_
#define mangle_pdrow2col             pdrow2col

#define F77_PDTREECOMB               pdtreecomb_
#define mangle_pdtreecomb            pdtreecomb

#define F77_PICHEKPAD                pichekpad_
#define mangle_pichekpad             pichekpad

#define F77_PICOL2ROW                picol2row_
#define mangle_picol2row             picol2row

#define F77_PIELGET                  pielget_
#define mangle_pielget               pielget

#define F77_PIELSET                  pielset_
#define mangle_pielset               pielset

#define F77_PIELSET2                 pielset2_
#define mangle_pielset2              pielset2

#define F77_PIFILLPAD                pifillpad_
#define mangle_pifillpad             pifillpad

#define F77_PILAPRNT                 pilaprnt_
#define mangle_pilaprnt              pilaprnt

#define F77_PIROW2COL                pirow2col_
#define mangle_pirow2col             pirow2col

#define F77_PITREECOMB               pitreecomb_
#define mangle_pitreecomb            pitreecomb

#define F77_PSCHEKPAD                pschekpad_
#define mangle_pschekpad             pschekpad

#define F77_PSCOL2ROW                pscol2row_
#define mangle_pscol2row             pscol2row

#define F77_PSELGET                  pselget_
#define mangle_pselget               pselget

#define F77_PSELSET                  pselset_
#define mangle_pselset               pselset

#define F77_PSELSET2                 pselset2_
#define mangle_pselset2              pselset2

#define F77_PSFILLPAD                psfillpad_
#define mangle_psfillpad             psfillpad

#define F77_PSLAPRNT                 pslaprnt_
#define mangle_pslaprnt              pslaprnt

#define F77_PSLAREAD                 pslaread_
#define mangle_pslaread              pslaread

#define F77_PSLAWRITE                pslawrite_
#define mangle_pslawrite             pslawrite

#define F77_PSMATADD                 psmatadd_
#define mangle_psmatadd              psmatadd

#define F77_PSROW2COL                psrow2col_
#define mangle_psrow2col             psrow2col

#define F77_PSTREECOMB               pstreecomb_
#define mangle_pstreecomb            pstreecomb

#define F77_PZCHEKPAD                pzchekpad_
#define mangle_pzchekpad             pzchekpad

#define F77_PZCOL2ROW                pzcol2row_
#define mangle_pzcol2row             pzcol2row

#define F77_PZELGET                  pzelget_
#define mangle_pzelget               pzelget

#define F77_PZELSET                  pzelset_
#define mangle_pzelset               pzelset

#define F77_PZELSET2                 pzelset2_
#define mangle_pzelset2              pzelset2

#define F77_PZFILLPAD                pzfillpad_
#define mangle_pzfillpad             pzfillpad

#define F77_PZLAPRNT                 pzlaprnt_
#define mangle_pzlaprnt              pzlaprnt

#define F77_PZLAREAD                 pzlaread_
#define mangle_pzlaread              pzlaread

#define F77_PZLAWRITE                pzlawrite_
#define mangle_pzlawrite             pzlawrite

#define F77_PZMATADD                 pzmatadd_
#define mangle_pzmatadd              pzmatadd

#define F77_PZROW2COL                pzrow2col_
#define mangle_pzrow2col             pzrow2col

#define F77_PZTREECOMB               pztreecomb_
#define mangle_pztreecomb            pztreecomb

#define F77_SLATCPY                  slatcpy_
#define mangle_slatcpy               slatcpy

#define F77_SLTIMER                  sltimer_
#define mangle_sltimer               sltimer

#define F77_SMATADD                  smatadd_
#define mangle_smatadd               smatadd

#define F77_SSDOT                    ssdot_
#define mangle_ssdot                 ssdot

#define F77_ZLATCPY                  zlatcpy_
#define mangle_zlatcpy               zlatcpy

#define F77_ZMATADD                  zmatadd_
#define mangle_zmatadd               zmatadd

#define F77_ZZDOTC                   zzdotc_
#define mangle_zzdotc                zzdotc

#define F77_ZZDOTU                   zzdotu_
#define mangle_zzdotu                zzdotu


#endif /* _WIN32 */

#endif /* AOCL_TOOLS_MANGLE_FUNCTION_PROTOTYPES_H */
